name: Subgraph tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "subgraph/**"

defaults:
  run:
    working-directory: ./subgraph

jobs:
  compilation:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Node dependencies cache
        uses: actions/cache@v3
        with:
          path: "subgraph/node_modules"
          key: yarn-${{ hashFiles('subgraph/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run codegen
        run: yarn codegen

      - name: Compile subgraph
        run: yarn build
