name: Create new Morpho Users distribution

on:
  workflow_dispatch
  schedule:
    - cron: '0 16 * * *'

jobs:
  compute-market-distribution:
    name: Compute markets users distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Compute Market Distribution
        run: yarn users:distribute
        env:
          RPC_URL: ${{ secrets.RPC_URL }}

      - name: Commit new users distribution to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Morpho GitHub Actions Bot
          commit_user_email: dev@morpho.xyz
          commit_message: Generate new users distribution for rewards
